### ISSUE TITLE
Parsing decimal error?

### ISSUE THREAD

**Issue by crazyyanchao** [neo4j/neo4j-jdbc#169]
I stored decimals in the neo4j database and reported an error while using Java jdbc access
```
java.sql.SQLException: An SQLException was provoked by the following failure: org.neo4j.driver.v1.exceptions.value.LossyCoercion: Cannot coerce FLOAT to Java float without losing precision
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:74)
code location: search.getString(i)
 while (search.next()) {
                columnNum = search.getMetaData().getColumnCount();
                for (int i = 1; i <= columnNum; i++) { 
                    stringList.add(search.getString(i));
                }
```

**Comment by crazyyanchao** [comment]
already solved
