### ISSUE TITLE
Parsing decimal error

### ISSUE THREAD

**Issue by crazyyanchao** [neo4j/neo4j-jdbc#170]
I stored decimals in the neo4j database and reported an error while using Java jdbc access
```
java.sql.SQLException: An SQLException was provoked by the following failure: org.neo4j.driver.v1.exceptions.value.LossyCoercion: Cannot coerce FLOAT to Java float without losing precision
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:74)
code location: search.getString(i)
 while (search.next()) {
                columnNum = search.getMetaData().getColumnCount();
                for (int i = 1; i <= columnNum; i++) { 
                    stringList.add(search.getString(i));
                }
```
And then  I try convert to JSON but fail
search.getObject(i) demo data (how to convert to JSON):
```
{influenceScore=542.19896, eid=1541, dep_id=1, create_time=2018-07-31 23:59:59, end_time=2018-07-31 23:59:59, start_time=2018-06-01 00:00:00, user_id=299, name=week thing, influenceScorePercentage=0.999723, _id=20311, category=17, _labels=[Label1, Label2], status=1}
```

**Comment by omarlarus** [comment]
Hi @crazyyanchao ,
can you provide us the Cypher code used to create the data and the whole java code (sql query + resultStatement management), please?
The JSON problem is not clear, we need some more details. If it isn't related to the "float" problem, it's worth to create another issue.

**Comment by crazyyanchao** [comment]
> Hi @crazyyanchao ,
> can you provide us the Cypher code used to create the data and the whole java code (sql query + resultStatement management), please?
> The JSON problem is not clear, we need some more details. If it isn't related to the "float" problem, it's worth to create another issue.

I query <MATCH (n:Label1) RETURN n LIMIT 10>   // !!! 1.The attributes of the node have decimals.  2.search.getObject Cannot convert to JSON!

Attachments are the means of parsing the result set.
```
package casia.isiteam.knowledgegraph.common.model;
import casia.isiteam.knowledgegraph.services.visualinter.Neo4jDataUtils;
import casia.isiteam.knowledgegraph.utils.DbUtil;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.mchange.v2.c3p0.ComboPooledDataSource;
import org.apache.log4j.Logger;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class Test {

    private static Logger logger = Logger.getLogger(Test.class);

    public static JSONObject exetueCypherJDBC(String cypher) {
        logger.info(cypher);
        JSONObject jsonObject = null;
        Connection con = null;
        PreparedStatement pre = null;
        ResultSet result = null;
        try {
            long startTime = System.nanoTime();
            ComboPooledDataSource dataSourcePool = DbUtil.getConNeo4jPool();
            con = dataSourcePool.getConnection();
            pre = con.prepareStatement(cypher);
            result = pre.executeQuery();
            jsonObject = getNeo4jResult(result);
            long endTime = System.nanoTime();
            long consume = (endTime - startTime) / 1000000;
            logger.info("Cypher match " + consume + "ms");
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            DbUtil.closeAll(result, pre, con);
        }
        return jsonObject;
    }

    public static JSONObject getNeo4jResult(ResultSet search) {
        // 遍历结果
        JSONObject results = new JSONObject(); //Final result
        JSONArray neoResults = new JSONArray();  //data array
        JSONObject result = new JSONObject(); //result
        JSONArray data = new JSONArray();  //data array
        JSONObject graph = new JSONObject(); //graph object
        JSONObject datas = new JSONObject(); //datas object

        JSONArray nodes = new JSONArray();
        JSONArray relationShips = new JSONArray();
        try {

            int columnNum;
            List<String> stringList = new ArrayList<String>();
            int stringListSize;
            String str;
            Object jsonData = null;

            while (search.next()) {
                columnNum = search.getMetaData().getColumnCount();
                for (int i = 1; i <= columnNum; i++) {  // (p1,p2,p3,p4,p5...n1,n2,n3,n4,n5...)

                    // search.getString error When I execute the node query <MATCH (n:Label1) RETURN 10 LIMIT 10>
                    // !!! The attributes of the node have decimals
                    stringList.add(search.getString(i));

                }
                stringListSize = stringList.size();
                for (int i = 0; i < stringListSize; i++) {
                    str = stringList.get(i);
                    if (str != null) {
                        //结果转换成array
                        try {
                            jsonData = JSON.parse(str);
                        } catch (Exception e) {
                            System.out.println("返回数据时错误的str：" + str);
                        }
                        //遍历结果
                        if (jsonData != null) {
                            JSONObject resultList = new JSONObject();
                            //判断结果为点还是线
                            // 返回路径
                            if (jsonData instanceof JSONArray) { //如果是 jsonArray 则为线
                                resultList = Neo4jDataUtils.getPathData(jsonData);
                                for (Object value : resultList.getJSONArray("nodes")) {
                                    if (!nodes.contains(value)) {
                                        nodes.add(value);
                                    }
                                }
                                for (Object value : resultList.getJSONArray("relationships")) {
                                    if (!relationShips.contains(value)) {
                                        relationShips.add(value);
                                    }
                                }
                            } else if (jsonData instanceof JSONObject) { //否则为点
                                // 返回节点
                                resultList = Neo4jDataUtils.getNodeData(jsonData);
                                if (!nodes.contains(resultList)) {
                                    nodes.add(resultList);
                                }
                            }
                        }
                    }
                }
                stringList.clear();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        datas.put("nodes", nodes);
        datas.put("relationships", relationShips);
        graph.put("graph", datas);
        data.add(graph);
        result.put("columns", "");
        result.put("data", data);
        neoResults.add(result);
        results.put("results", neoResults);
        return results;
    }
}

```

**Comment by omarlarus** [comment]
Hi @crazyyanchao ,
when you execute the Cypher statement "`MATCH (n:Label1) RETURN 10 LIMIT 10`" the database return to you the number "10" because there's no variables in the "`RETURN`" clause. However, even if you did a typo and the query is "`MATCH (n:Label1) RETURN n LIMIT 10`", when you call the column count you have 1 and it means the *node* (n), and it throws the exception you wrote. We're looking for the error in order to manage this situation better than now (in the 3.4 version).

Looking to your code you can fix it executing this Cypher statement "`MATCH (n:Label1) RETURN n LIMIT 10`" and use the `getObject` method that returns a `Map<String,Object>` when the output is a node.

**Comment by crazyyanchao** [comment]
> Hi @crazyyanchao ,
> when you execute the Cypher statement "`MATCH (n:Label1) RETURN 10 LIMIT 10`" the database return to you the number "10" because there's no variables in the "`RETURN`" clause. However, even if you did a typo and the query is "`MATCH (n:Label1) RETURN n LIMIT 10`", when you call the column count you have 1 and it means the _node_ (n), and it throws the exception you wrote. We're looking for the error in order to manage this situation better than now (in the 3.4 version).
> 
> Looking to your code you can fix it executing this Cypher statement "`MATCH (n:Label1) RETURN n LIMIT 10`" and use the `getObject` method that returns a `Map<String,Object>` when the output is a node.

I typed the wrong code ~.~.  MATCH (n:Label1) RETURN n LIMIT 10
But, search.getObject convert to JSON ERROR! 
Ok,I try map! 
Thanks

**Comment by crazyyanchao** [comment]
Thanks @omarlarus 
I typed the wrong code ~.~.  MATCH (n:Label1) RETURN n LIMIT 10
But, search.getObject convert to JSON ERROR! 
I need to transform relationships and nodes to JSON.
NODE is {OBJECT}, RELATIONSHIP is []!
How to use a method to solve? It soupport to convert n and p! I can not understand！

**Comment by omarlarus** [comment]
Hi @crazyyanchao ,
you can choose 2 ways: 

- `rs.getObject(int):Map<String,Object>` if the parameter is a node or a relationship you get a map with the values inside them and then convert it into a JSON.
- `rs.getString(int):String` if the parameter is a node or a relationship you get a JSON string representing the content. This feature in your case has a bug we're solving today.

If you need a quick preview I can send you a jar of the developer version of jdbc driver 3.4.

**Comment by crazyyanchao** [comment]
@omarlarus Please send it to my email address，Thanks! 
EMAIL: yanchaoma@foxmail.com

**Comment by omarlarus** [comment]
@crazyyanchao  you can download a preview with the fix [here](https://www.dropbox.com/s/zmfusedt4yorchw/neo4j-jdbc-driver-3.4.0_170.jar?dl=0)

**Comment by crazyyanchao** [comment]
Thanks @omarlarus 
I get a error, How to fix it?
```
java.lang.NoSuchMethodError: org.neo4j.driver.internal.types.InternalTypeSystem.DATE()Lorg/neo4j/driver/v1/types/Type;
	at org.neo4j.jdbc.bolt.BoltNeo4jResultSetMetaData.<clinit>(BoltNeo4jResultSetMetaData.java:58) ~[neo4j-jdbc-driver-3.4.0.170.jar:na]
	at org.neo4j.jdbc.bolt.BoltNeo4jResultSet.<init>(BoltNeo4jResultSet.java:103) ~[neo4j-jdbc-driver-3.4.0.170.jar:na]
	at org.neo4j.jdbc.bolt.BoltNeo4jResultSet.newInstance(BoltNeo4jResultSet.java:107) ~[neo4j-jdbc-driver-3.4.0.170.jar:na]
	at org.neo4j.jdbc.bolt.BoltNeo4jPreparedStatement.executeQuery(BoltNeo4jPreparedStatement.java:63) ~[neo4j-jdbc-driver-3.4.0.170.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]
	at org.neo4j.jdbc.utils.Neo4jInvocationHandler.invoke(Neo4jInvocationHandler.java:54) ~[neo4j-jdbc-driver-3.4.0.170.jar:na]
	at com.sun.proxy.$Proxy70.executeQuery(Unknown Source) ~[na:na]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:353) ~[c3p0-0.9.5.2.jar:0.9.5.2]
	at casia.isiteam.knowledgegraph.repository.CypherNeo4jOperation.exetueCypherJDBC(CypherNeo4jOperation.java:743) ~[classes/:na]
	at casia.isiteam.knowledgegraph.services.DataServiceImpl.multiEntitiesFuzzyCrossMatch(DataServiceImpl.java:1794) ~[classes/:na]
	at casia.isiteam.knowledgegraph.controller.HelloController.multiEntitiesCrossMatch(HelloController.java:462) ~[classes/:na]
```

My pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>casia.isiteam</groupId>
    <artifactId>knowledge-graph</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>knowledge-graph</name>
    <description>Knowledge graph demo project for Spring Boot</description>

    <!--起步依赖-->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.0.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.ecf</groupId>
            <artifactId>org.apache.log4j</artifactId>
            <version>1.2.15.v201012070815</version>
        </dependency>
        <!-- 数据库连接池 -->
        <dependency>
            <groupId>com.mchange</groupId>
            <artifactId>c3p0</artifactId>
            <version>0.9.5.2</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.30</version>
        </dependency>
        <!--开发WEB项目相关依赖-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!--SpringBoot单元测试-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <!--Spring Boot默认就是使用thymeleaf模板引擎-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <!-- https://mvnrepository.com/artifact/dom4j/dom4j -->
        <dependency>
            <groupId>dom4j</groupId>
            <artifactId>dom4j</artifactId>
            <version>1.6.1</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.alibaba/fastjson -->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.47</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.neo4j/neo4j -->
        <!--<dependency>-->
            <!--<groupId>org.neo4j</groupId>-->
            <!--<artifactId>neo4j</artifactId>-->
            <!--<version>3.3.2</version>-->
        <!--</dependency>-->
        <!-- https://mvnrepository.com/artifact/org.neo4j/neo4j -->
        <dependency>
            <groupId>org.neo4j</groupId>
            <artifactId>neo4j</artifactId>
            <version>3.4.7</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.neo4j.driver/neo4j-java-driver -->
        <dependency>
            <groupId>org.neo4j.driver</groupId>
            <artifactId>neo4j-java-driver</artifactId>
            <version>1.5.1</version>
        </dependency>
        <dependency>
            <groupId>casia.isiteam.ga</groupId>
            <artifactId>nn_es_indexer</artifactId>
            <version>1.0.0</version>
        </dependency>
        <!-- Elasticsearch delete-by-query安装包导入 -->
        <dependency>
            <groupId>org.elasticsearch.plugin</groupId>
            <artifactId>delete-by-query</artifactId>
            <version>2.3.4</version>
        </dependency>

         <!--https://mvnrepository.com/artifact/org.neo4j/neo4j-jdbc-driver-->
        <!--<dependency>-->
        <!--<groupId>org.neo4j</groupId>-->
        <!--<artifactId>neo4j-jdbc-driver</artifactId>-->
        <!--<version>3.3.1</version>-->
        <!--</dependency>-->
        <!--修复解析小数的BUG-->
        <dependency>
            <groupId>casia.isi.zdr.neo4j</groupId>
            <artifactId>neo4j-jdbc-driver</artifactId>
            <version>3.4.0.170</version>
        </dependency>

    </dependencies>
    <!--MAVEN构建-->
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <!-- 拷贝依赖的jar包到lib目录 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>
                                ${project.build.directory}/lib
                            </outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <!-- 解决使用maven update project java版本自动切换问题 -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

```

**Comment by omarlarus** [comment]
@crazyyanchao  I sent you the 3.4 version of jdbc driver, that need the 1.6.1 version of neo4j-java-driver.

Try to change the dependency, please
```
        <dependency>
            <groupId>org.neo4j.driver</groupId>
            <artifactId>neo4j-java-driver</artifactId>
            <version>1.6.1</version>
        </dependency>
```

PS: you can check the dependencies looking at [here](https://github.com/neo4j-contrib/neo4j-jdbc/tree/3.4) in the README section.

**Comment by crazyyanchao** [comment]
@omarlarus OK, Thanks!

**Comment by jexp** [comment]
Merged the pull request, will be in the next release.
