### ISSUE TITLE
Giving exception if Labels contains space

### ISSUE THREAD

**Issue by pradipborde** [neo4j/neo4j-jdbc#181]
I am getting below error for any syntax error in any query. When looked into code issue seems with the way it is written without quotes in getDatabaseProperties(BoltNeo4jDatabaseMetaData.java:102) while spring jdbc tries to translate the error codes. Connection.getMetaData method always fails if any of the Label in db contains space.

2019-01-22 18:07:55.385 ERROR 11328 --- [nio-8043-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.neo4j.driver.v1.exceptions.ClientException: Invalid input 'U': expected whitespace, comment, NodeLabel, MapLiteral, a parameter, ')' or a relationship pattern (line 1, column 19 (offset: 18))
"MATCH (n:Business Unit) WITH n LIMIT 1000 UNWIND keys(n) as key RETURN collect(distinct key) as keys"
                   ^] with root cause

org.neo4j.driver.v1.exceptions.ClientException: Invalid input 'U': expected whitespace, comment, NodeLabel, MapLiteral, a parameter, ')' or a relationship pattern (line 1, column 19 (offset: 18))
"MATCH (n:Business Unit) WITH n LIMIT 1000 UNWIND keys(n) as key RETURN collect(distinct key) as keys"
                   ^
	at org.neo4j.driver.internal.net.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:76) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:470) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:431) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at org.neo4j.driver.internal.net.SocketClient.receiveOne(SocketClient.java:196) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at org.neo4j.driver.internal.net.SocketConnection.receiveOne(SocketConnection.java:217) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at org.neo4j.driver.internal.net.ConcurrencyGuardingConnection.receiveOne(ConcurrencyGuardingConnection.java:165) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at org.neo4j.driver.internal.net.pooling.PooledSocketConnection.receiveOne(PooledSocketConnection.java:183) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at org.neo4j.driver.internal.InternalStatementResult.receiveOne(InternalStatementResult.java:335) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at org.neo4j.driver.internal.InternalStatementResult.tryFetchNext(InternalStatementResult.java:325) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at org.neo4j.driver.internal.InternalStatementResult.hasNext(InternalStatementResult.java:193) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at org.neo4j.jdbc.bolt.BoltNeo4jDatabaseMetaData.cycleResultSetToSetDatabaseProperties(BoltNeo4jDatabaseMetaData.java:109) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at org.neo4j.jdbc.bolt.BoltNeo4jDatabaseMetaData.getDatabaseProperties(BoltNeo4jDatabaseMetaData.java:102) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at org.neo4j.jdbc.bolt.BoltNeo4jDatabaseMetaData.<init>(BoltNeo4jDatabaseMetaData.java:62) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at org.neo4j.jdbc.bolt.impl.BoltNeo4jConnectionImpl.getMetaData(BoltNeo4jConnectionImpl.java:95) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at org.neo4j.jdbc.bolt.impl.BoltNeo4jConnectionImpl.getMetaData(BoltNeo4jConnectionImpl.java:46) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.neo4j.jdbc.utils.Neo4jInvocationHandler.invoke(Neo4jInvocationHandler.java:54) ~[neo4j-jdbc-driver-3.3.1.jar:na]
	at com.sun.proxy.$Proxy136.getMetaData(Unknown Source) ~[na:na]
	at com.zaxxer.hikari.pool.ProxyConnection.getMetaData(ProxyConnection.java:361) ~[HikariCP-2.7.9.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyConnection.getMetaData(HikariProxyConnection.java) ~[HikariCP-2.7.9.jar:na]
	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:320) ~[spring-jdbc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:356) ~[spring-jdbc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jdbc.support.SQLErrorCodesFactory.getErrorCodes(SQLErrorCodesFactory.java:214) ~[spring-jdbc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.setDataSource(SQLErrorCodeSQLExceptionTranslator.java:136) ~[spring-jdbc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.<init>(SQLErrorCodeSQLExceptionTranslator.java:99) ~[spring-jdbc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jdbc.support.JdbcAccessor.getExceptionTranslator(JdbcAccessor.java:122) ~[spring-jdbc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1402) ~[spring-jdbc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:620) ~[spring-jdbc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:657) ~[spring-jdbc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:682) ~[spring-jdbc-5.0.7.RELEASE.jar:5.0.7.RELEASE]

**Comment by conker84** [comment]
Hi @pradipborde and thanks a lot for reporting this.
Can you try with this jar, and give us feedback?
[neo4j-jdbc-driver-3.3.1.jar.zip](https://github.com/neo4j-contrib/neo4j-jdbc/files/2788174/neo4j-jdbc-driver-3.3.1.jar.zip)

**Comment by pradipborde** [comment]
@conker84 
Thanks Andrea, This does work well with syntax errors. Can you update this patch on the GitHub repo and upload it on Maven.

**Comment by conker84** [comment]
Closed via 641c16b1170e65a72d4600a1548dcb7bd77f0d51
