### ISSUE TITLE
Issue about BoltDriver

### ISSUE THREAD

**Issue by p0pfan** [neo4j/neo4j-jdbc#221]
Hi guys, this is an issue about using Neo4j JDBC Driver.
the Neo4j JDBC Driver version is `3.4.0`
the Neo4j Server version : `neo4j-community-3.5.8`

1. the method to get connection
```java
    private void initConnection(boolean isBolt, String neo4jUrl){
        try {
            if(connection == null || connection.isClosed()){
                synchronized (Neo4jTest.class) {
                    if(connection == null || connection.isClosed()){
                        URL url = Thread.currentThread().getContextClassLoader().getResource("neo4j-jdbc-driver-3.4.0.jar");
                        URLClassLoader neo4jClassLoader = new URLClassLoader(new URL[]{url}, Thread.currentThread()
                                .getContextClassLoader());
                        Driver driver;
                        if (isBolt) {
                            driver = (Driver) neo4jClassLoader.loadClass("org.neo4j.jdbc.bolt.BoltDriver").newInstance();
                        } else {
                            driver = (Driver) neo4jClassLoader.loadClass("org.neo4j.jdbc.http.HttpDriver").newInstance();

                        }
                        Properties info = new Properties();
                        info.put("user", "neo4j");
                        info.put("password", "neo4jneo4j");
                        connection = driver.connect(neo4jUrl, info);
                    }
                }
            }
        } catch (ClassNotFoundException e) {
            log.warn(e.getMessage());
        } catch (SQLException e) {
            log.warn(e.getMessage());
        } catch (IllegalAccessException e) {
            log.warn(e.getMessage());
        } catch (InstantiationException e) {
            log.warn(e.getMessage());
        }
    }

    protected Connection getConnection(){
        try {
            if(connection == null || connection.isClosed()){
                initConnection(isBolt, url);
            }
        } catch (SQLException e) {
            log.info(e.getMessage());
            initConnection(isBolt, url);
        }
        return connection;
    }
```
2. the executeQuery method
```java
    protected ResultSet executeQueryReturnResultSet(String cypher) throws SQLException {
        Statement statement = getConnection().createStatement();
        ResultSet set = statement.executeQuery(cypher);
        System.out.println("Done!!");
        return set;
    }
```

### BoltDriver Exception
```java
        public static ExecutorService AsyncExecutor = Executors.newFixedThreadPool(2);
        AsyncExecutor.submit(() -> {
            try {
                neo4jTest.executeQueryReturnResultSet(UPDATE_CYPHER);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        });
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        AsyncExecutor.submit(() -> {
            try {
                neo4jTest.executeQueryReturnResultSet(QUERY_CYPHER);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        });
        AsyncExecutor.submit(() -> {
            try {
                neo4jTest.executeQueryReturnResultSet(QUERY_CYPHER);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        });

```

the exception is

```java
java.sql.SQLException: org.neo4j.driver.v1.exceptions.ClientException: No current transaction to commit.
	at org.neo4j.jdbc.bolt.BoltNeo4jStatement.executeInternal(BoltNeo4jStatement.java:111)
	at org.neo4j.jdbc.bolt.BoltNeo4jStatement.executeQuery(BoltNeo4jStatement.java:64)
	at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

```

---

BTW, I have uploaded the test file to  replicate the issue

[test.zip](https://github.com/neo4j-contrib/neo4j-jdbc/files/4359685/test.zip)

**Comment by jexp** [comment]
Could you please split two issues into two isssue.

In general, please use the neo4j-java-driver for programmatic usage not the jdbc driver.
The JDBC driver is more meant for tools and integrations.

**Comment by p0pfan** [comment]
> Could you please split two issues into two isssue.
> 
> In general, please use the neo4j-java-driver for programmatic usage not the jdbc driver.
> The JDBC driver is more meant for tools and integrations.

I have  split two into two issue.
another is here: https://github.com/neo4j-contrib/neo4j-jdbc/issues/222

**Comment by conker84** [comment]
You should create a Connection instance in this way:

`DriverManager.getConnection("jdbc:neo4j:bolt://localhost:7687", "neo4j", "foo")` in each thread, we 

have an internal caching mechanism that reuse the same`Driver` instance an create a new `Session` for each thread

**Comment by p0pfan** [comment]
@jexp @conker84 thank you for your reply. And both solutions work for me.
