### ISSUE TITLE
executeQuery with invalid cypher doesn't throw SQLException

### ISSUE THREAD

**Issue by mvitz** [neo4j/neo4j-jdbc#23]
I expected that
`Statement stmt = connection.createStatement();
stmt.executeQuery("fooBar"):`
throws an SQLException but instead a Neo4J Internal Exception is thrown.

See https://github.com/mvitz/neo4j-jdbc/commit/53eb06f207c5a7f5bff108786033ee30fe76046a for a failing test.

**Comment by jexp** [comment]
With which transport?

Von meinem iPhone gesendet

**Comment by mvitz** [comment]
I tested IT with bolt. But looking at the implementation I guess HTTP throws an internal exception instead of SQLException as well

**Comment by sim51** [comment]
Bug is fix in master branch for Bolt & HTTP

**Comment by jexp** [comment]
Thanks a lot @sim51 ! @mvitz can you confirm that it's fixed?

**Comment by mvitz** [comment]
👍

**Comment by mvitz** [comment]
I don't know why but suddenly the bug occurs again (but on a slightly different position:

```
Stacktrace was: org.neo4j.driver.v1.exceptions.ClientException: Invalid input 't': expected <init> (line 1, column 1 (offset: 0))
"toto"
 ^
    at org.neo4j.driver.internal.connector.socket.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:68)
    at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:456)
    at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:417)
    at org.neo4j.driver.internal.connector.socket.SocketClient.receiveOne(SocketClient.java:127)
    at org.neo4j.driver.internal.connector.socket.SocketConnection.receiveOne(SocketConnection.java:135)
    at org.neo4j.driver.internal.connector.ConcurrencyGuardingConnection.receiveOne(ConcurrencyGuardingConnection.java:150)
    at org.neo4j.driver.internal.pool.PooledConnection.receiveOne(PooledConnection.java:142)
    at org.neo4j.driver.internal.InternalStatementResult.tryFetchNext(InternalStatementResult.java:303)
    at org.neo4j.driver.internal.InternalStatementResult.hasNext(InternalStatementResult.java:181)
    at org.neo4j.jdbc.bolt.BoltResultSet.<init>(BoltResultSet.java:79)
    at org.neo4j.jdbc.bolt.BoltStatement.executeQuery(BoltStatement.java:88)
```

**Comment by sim51** [comment]
It's weird ... and I cant' reproduce it, even with the unit test (https://github.com/neo4j-contrib/neo4j-jdbc/blob/master/neo4j-jdbc-bolt/src/test/java/org/neo4j/jdbc/bolt/BoltStatementIT.java#L101-L112)

@mvitz What query have you used ?

**Comment by mvitz** [comment]
I'm investigating this...
The Test has a small bug btw. the URL doesn't contain the new `jdbc:neo4j:`-Prefix but even after fixing this I'm not able to produce it with this test...

**Comment by mvitz** [comment]
It has to do with `setAutoComit(false`...

Add the following snippet for a failing test:

```
    @Test public void executeBadCypherQueryWithoutAutoCommitShouldReturnAnSQLException() throws
            SQLException {
        expectedEx.expect(SQLException.class);

        Connection connection = DriverManager.getConnection("jdbc:neo4j:" + neo4j.getBoltUrl());
        connection.setAutoCommit(false);
        Statement statement = connection.createStatement();
        try {
            statement.execute("AZERTYUIOP");
        }
        finally {
            connection.close();
        }
    }
```

**Comment by sim51** [comment]
Thanks a lot @mvitz !

PS: I have seen the little bug on the url, so I have added a condition on the error message.
