### ISSUE TITLE
JDBC driver should relocate shaded libraries

### ISSUE THREAD

**Issue by martintreurnicht** [neo4j/neo4j-jdbc#321]
We've recently ran into an issue with fabric 8 client not being able to find jackson method:

```shell
Exception in thread "OkHttp Dispatcher" java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.util.JacksonFeatureSet com.fasterxml.jackson.core.JsonParser.getReadCapabilities()'
	at com.fasterxml.jackson.databind.DeserializationContext.<init>(DeserializationContext.java:211)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.<init>(DefaultDeserializationContext.java:50)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl.<init>(DefaultDeserializationContext.java:391)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl.createInstance(DefaultDeserializationContext.java:413)
	at com.fasterxml.jackson.databind.ObjectMapper.createDeserializationContext(ObjectMapper.java:4654)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4583)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3591)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:261)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:184)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:170)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.readWatchEvent(AbstractWatchManager.java:200)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:225)
	at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:93)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
After a lot of debugging, we found the `neo4j-jdbc-driver` is including it's own copy of jackson, which is out of date. This is a huge problem that is very hard to detect.

The correct way to shade libraries like this would be to [relocate the classes](https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html), this is what gRPC and other major libraries have done for many years.

Hope this helps others that are struggling with this same issue

**Comment by fbiville** [comment]
Following the discussion in the PR, I think we can close this issue. Please reopen if you think otherwise.
