### ISSUE TITLE
play.api.PlayException: Cannot load Driver[Driver [org.neo4j.jdbc.BaseDriver] cannot be instantiated.]

### ISSUE THREAD

**Issue by jasperdenkers** [neo4j/neo4j-jdbc#65]
I'm trying to use the neo4j-jdbc driver with Play 2.5.

In `build.sbt` I have the following dependencies:
- `javaJdbc`
- `"org.neo4j" % "neo4j-jdbc" % "3.0"`

I've configured a database named neo4j in `application.conf`:

```
# Neo4j database configuration
db.neo4j.driver=org.neo4j.jdbc.BaseDriver
db.neo4j.url="jdbc:neo4j:bolt://localhost"
```

And just started trying out the setup using the following controller:

```
package controllers

import javax.inject.Inject
import play.api.db.{ Database, NamedDatabase }
import play.api.mvc._

class Neo4j @Inject()(@NamedDatabase("neo4j") neo4j: Database) extends Controller {

  def index = Action {
    Ok(neo4j.name)
  }

}
```

At first I had `db.neo4j.driver=org.neo4j.jdbc.Driver` as in [this example](https://github.com/neo4j-contrib/neo4j-jdbc/blob/master/docs/play.adoc) but this seemed to be renamed in the 3.0 release. However, the driver can not be instantiated:

```
play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [neo4j]]
        at play.api.Configuration$.configError(Configuration.scala:154)
        at play.api.Configuration.reportError(Configuration.scala:806)
        at play.api.db.DefaultDBApi$$anonfun$connect$1.apply(DefaultDBApi.scala:48)
        at play.api.db.DefaultDBApi$$anonfun$connect$1.apply(DefaultDBApi.scala:42)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at play.api.db.DefaultDBApi.connect(DefaultDBApi.scala:42)
        at play.api.db.DBApiProvider.get$lzycompute(DBModule.scala:72)
        at play.api.db.DBApiProvider.get(DBModule.scala:62)
        at play.api.db.DBApiProvider.get(DBModule.scala:58)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
Caused by: play.api.Configuration$$anon$1: Configuration error[Driver not found: [org.neo4j.jdbc.BaseDriver}]]
        at play.api.Configuration$.configError(Configuration.scala:154)
        at play.api.PlayConfig.reportError(Configuration.scala:996)
        at play.api.db.DefaultDatabase$$anonfun$driver$1.apply(Databases.scala:115)
        at play.api.db.DefaultDatabase$$anonfun$driver$1.apply(Databases.scala:109)
        at scala.Option.map(Option.scala:146)
        at play.api.db.DefaultDatabase.driver$lzycompute(Databases.scala:109)
        at play.api.db.DefaultDatabase.driver(Databases.scala:108)
        at play.api.db.DefaultDatabase.dataSource$lzycompute(Databases.scala:123)
        at play.api.db.DefaultDatabase.dataSource(Databases.scala:122)
        at play.api.db.DefaultDatabase.getConnection(Databases.scala:143)
Caused by: play.api.PlayException: Cannot load Driver[Driver [org.neo4j.jdbc.BaseDriver] cannot be instantiated.]
        at play.utils.Reflect$.createInstance(Reflect.scala:142)
        at play.api.db.DefaultDatabase$$anonfun$driver$1.apply(Databases.scala:111)
        at play.api.db.DefaultDatabase$$anonfun$driver$1.apply(Databases.scala:109)
        at scala.Option.map(Option.scala:146)
        at play.api.db.DefaultDatabase.driver$lzycompute(Databases.scala:109)
        at play.api.db.DefaultDatabase.driver(Databases.scala:108)
        at play.api.db.DefaultDatabase.dataSource$lzycompute(Databases.scala:123)
        at play.api.db.DefaultDatabase.dataSource(Databases.scala:122)
        at play.api.db.DefaultDatabase.getConnection(Databases.scala:143)
        at play.api.db.DefaultDatabase.getConnection(Databases.scala:139)
Caused by: java.lang.InstantiationException: org.neo4j.jdbc.BaseDriver
        at java.lang.Class.newInstance(Class.java:427)
        at play.utils.Reflect$.createInstance(Reflect.scala:154)
        at play.utils.Reflect$.createInstance(Reflect.scala:136)
        at play.api.db.DefaultDatabase$$anonfun$driver$1.apply(Databases.scala:111)
        at play.api.db.DefaultDatabase$$anonfun$driver$1.apply(Databases.scala:109)
        at scala.Option.map(Option.scala:146)
        at play.api.db.DefaultDatabase.driver$lzycompute(Databases.scala:109)
        at play.api.db.DefaultDatabase.driver(Databases.scala:108)
        at play.api.db.DefaultDatabase.dataSource$lzycompute(Databases.scala:123)
        at play.api.db.DefaultDatabase.dataSource(Databases.scala:122)
Caused by: java.lang.NoSuchMethodException: org.neo4j.jdbc.BaseDriver.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.newInstance(Class.java:412)
        at play.utils.Reflect$.createInstance(Reflect.scala:154)
        at play.utils.Reflect$.createInstance(Reflect.scala:136)
        at play.api.db.DefaultDatabase$$anonfun$driver$1.apply(Databases.scala:111)
        at play.api.db.DefaultDatabase$$anonfun$driver$1.apply(Databases.scala:109)
        at scala.Option.map(Option.scala:146)
        at play.api.db.DefaultDatabase.driver$lzycompute(Databases.scala:109)
        at play.api.db.DefaultDatabase.driver(Databases.scala:108)
        at play.api.db.DefaultDatabase.dataSource$lzycompute(Databases.scala:123)
```

**Comment by jexp** [comment]
Don't use BaseDriver but Driver

Von meinem iPhone gesendet

**Comment by jasperdenkers** [comment]
I did before but that one could not be found. Seemed I used the wrong dependency: `"org.neo4j" % "neo4j-jdbc" % "3.0"` instead of `"org.neo4j" % "neo4j-jdbc-driver" % "3.0"`. Now the error above is gone.

However, now I get the following error:

```
play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [neo4j]]
        at play.api.Configuration$.configError(Configuration.scala:154)
        at play.api.Configuration.reportError(Configuration.scala:806)
        at play.api.db.DefaultDBApi$$anonfun$connect$1.apply(DefaultDBApi.scala:48)
        at play.api.db.DefaultDBApi$$anonfun$connect$1.apply(DefaultDBApi.scala:42)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at play.api.db.DefaultDBApi.connect(DefaultDBApi.scala:42)
        at play.api.db.DBApiProvider.get$lzycompute(DBModule.scala:72)
        at play.api.db.DBApiProvider.get(DBModule.scala:62)
        at play.api.db.DBApiProvider.get(DBModule.scala:58)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
Caused by: play.api.Configuration$$anon$1: Configuration error[Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 30003ms.]
        at play.api.Configuration$.configError(Configuration.scala:154)
        at play.api.PlayConfig.reportError(Configuration.scala:996)
        at play.api.db.HikariCPConnectionPool.create(HikariCPModule.scala:69)
        at play.api.db.PooledDatabase.createDataSource(Databases.scala:200)
        at play.api.db.DefaultDatabase.dataSource$lzycompute(Databases.scala:124)
        at play.api.db.DefaultDatabase.dataSource(Databases.scala:122)
        at play.api.db.DefaultDatabase.getConnection(Databases.scala:143)
        at play.api.db.DefaultDatabase.getConnection(Databases.scala:139)
        at play.api.db.DefaultDBApi$$anonfun$connect$1.apply(DefaultDBApi.scala:44)
        at play.api.db.DefaultDBApi$$anonfun$connect$1.apply(DefaultDBApi.scala:42)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 30003ms.
        at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:526)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:136)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
        at play.api.db.HikariCPConnectionPool$$anonfun$1.apply(HikariCPModule.scala:58)
        at play.api.db.HikariCPConnectionPool$$anonfun$1.apply(HikariCPModule.scala:54)
        at scala.util.Try$.apply(Try.scala:192)
        at play.api.db.HikariCPConnectionPool.create(HikariCPModule.scala:54)
        at play.api.db.PooledDatabase.createDataSource(Databases.scala:200)
        at play.api.db.DefaultDatabase.dataSource$lzycompute(Databases.scala:124)
        at play.api.db.DefaultDatabase.dataSource(Databases.scala:122)
Caused by: java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 30003ms.
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:195)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
        at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:510)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:136)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
        at play.api.db.HikariCPConnectionPool$$anonfun$1.apply(HikariCPModule.scala:58)
        at play.api.db.HikariCPConnectionPool$$anonfun$1.apply(HikariCPModule.scala:54)
        at scala.util.Try$.apply(Try.scala:192)
        at play.api.db.HikariCPConnectionPool.create(HikariCPModule.scala:54)
        at play.api.db.PooledDatabase.createDataSource(Databases.scala:200)
Caused by: java.lang.UnsupportedOperationException: Method isValid in class org.neo4j.jdbc.Connection is not yet implemented.
        at org.neo4j.jdbc.utils.ExceptionBuilder.buildUnsupportedOperationException(ExceptionBuilder.java:41)
        at org.neo4j.jdbc.Connection.isValid(Connection.java:372)
        at com.zaxxer.hikari.pool.PoolBase.checkValidationMode(PoolBase.java:368)
        at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:336)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:315)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:171)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:436)
        at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:65)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:567)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:560)
```

The most relevant line seems `java.lang.UnsupportedOperationException: Method isValid in class org.neo4j.jdbc.Connection is not yet implemented.`. Any idea?

**Comment by sim51** [comment]
There is already an issue for the non-implemented method `isValid`. See issue #64

**Comment by glaggia-larus** [comment]
As Benoit pointed out this is related to issue #64, I mark this as duplicate, until #64 is resolved.

After the resolution of that, we'll verify if this issue is still open or not.

**Comment by glaggia-larus** [comment]
This should be fixed for **BOLT module** with c7acc09

A new snapshot version jar is available.

Can you please try it out and give us a feedback?

**Comment by inserpio** [comment]
We should make BaseDriver class protected

**Comment by jasperdenkers** [comment]
@glaggia-larus I can confirm the 3.0.1-SNAPSHOT jar works for me. I've tested this with SBT by removing the dependency from `build.sbt` and adding the jar to the `/lib` directory.

@inserpio Sounds like a good idea. Initially I was confused because I used the `"org.neo4j" % "neo4j-jdbc" % "3.0"` dependency instead of `"org.neo4j" % "neo4j-jdbc-driver" % "3.0"`. In my config Intellij did autocomplete `db.neo4j.driver=org.neo4j.jdbc.` to `BaseDriver` and not to `Driver` (because it was missing in the dependency). I think that won't happen if the class is protected.

**Comment by rubby33** [comment]
I come across a similar problem too. The boltDriver can not be found. so i use

```
DriverManager.registerDriver(driver); to solve the problem.

String driverName = "org.neo4j.jdbc.bolt.BoltDriver";

try {
            Class<?> driverClazz  = Class.forName(driverName);
            // test whether dirver class found
            boolean driverFound = false;
            Enumeration<Driver> drivers = DriverManager.getDrivers();
            // iterator all drivers
            while(drivers.hasMoreElements()){
                Driver driver = drivers.nextElement();
                if(driver.getClass().getName().equals(driverName)){
                    driverFound = true;
                    // stop the enumeration
                    break;
                }
            }
            // while driver not found, register driver
            if(!driverFound){
                Driver driver = (Driver) driverClazz.newInstance();
                DriverManager.registerDriver(driver);
            }
        } catch (ClassNotFoundException ce) {
            LOGGER.error(null, ce);
            throw new IllegalArgumentException("Unable to find driver in classpath", ce);
        } catch (InstantiationException e) {
            LOGGER.error(null, e); 
            throw new IllegalArgumentException("Unable to create driver", e);
        } catch (IllegalAccessException e) {
            LOGGER.error(null, e); 
            throw new IllegalArgumentException("Unable to create driver", e);
        } catch (SQLException e) {
            LOGGER.error(null, e); 
            throw new IllegalArgumentException("Unable to install driver", e);
        }
```

**Comment by inserpio** [comment]
Hi @rubby33, it shouldn't be necessary for you to register the driver. We detect the right driver instance (bolt or http) according to the connection url: i.e. `jdbc:neo4j:bolt://localhost` will return the bolt implementation, while `jdbc:neo4j:http://localhost` would return the http one.
The https://github.com/neo4j-contrib/neo4j-jdbc#minimum-viable-snippet should be enough.
Are you using the last snapshot version?
We'd like to close this issue to release a new official version of the driver with these small improvement and then take some time to work on improving the visibility of some classes (i.e. making the BaseDriver class protected, as we discussed above).

**Comment by rubby33** [comment]
hi, i did not use the latest version. i use the version of 10. July.
For the stability of our
system，we have test the driver for a while before use it。
If the latest version have fixed the problem,  that's cool. thanks

2016-07-26 17:01 GMT+08:00 Lorenzo Speranzoni notifications@github.com:

**Comment by tommystanton** [comment]
The initial cause of this issue (wrong artifact specified, as also incorrect in the README) is related to issue #72 (which has been resolved: README was updated).

**Comment by sim51** [comment]
Hi @rubby33 

So have you be able to test your code with the lastest build ?
Does it resolve your problem ?

Cheers.

**Comment by rubby33** [comment]
@sim51  yes，the lastest build works well. Thanks.
